# Generated by Django 4.0.5 on 2022-06-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bio_alter_customuser_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_img',
            field=models.ImageField(default='default.jpg', upload_to='profile-pics'),
        ),
    ]
