# Generated by Django 4.0.5 on 2022-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile-pics'),
        ),
    ]
