# Generated by Django 4.0.5 on 2022-06-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='default-book-cover.jpg', upload_to='book-cover'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_location',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Into the Matrix', 'into the matrix')], default='Into the Matrix', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_condition',
            field=models.CharField(choices=[('Physical', 'Phyiscal'), ('Digital', 'Digital')], default='Physical', max_length=20),
        ),
    ]
