# Generated by Django 4.0.5 on 2022-06-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_cover_book_book_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='titlename',
            field=models.CharField(default='apple', max_length=255),
        ),
    ]
