# Generated by Django 4.0.5 on 2022-06-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_titlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.TextField(default='Put book description'),
        ),
    ]
