# Generated by Django 4.0.5 on 2022-07-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ownerid',
            new_name='owner',
        ),
    ]
