# Generated by Django 4.0.5 on 2022-07-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_rename_ownerid_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
