# Generated by Django 4.0.5 on 2022-07-05 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0017_book_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='borrow_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_borrower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
