# Generated by Django 4.0.5 on 2022-07-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_book_book_available_book_book_return_book_borrow_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_return',
            field=models.BooleanField(default=True),
        ),
    ]
