# Generated by Django 4.0.5 on 2022-07-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_book_book_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
