# Generated by Django 4.0.5 on 2022-07-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_book_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='borrow_id',
            new_name='borrow',
        ),
    ]
