# Generated by Django 4.0.5 on 2022-07-06 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0022_remove_book_book_available_remove_book_book_return_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_available', models.BooleanField(default=True)),
                ('borrowed_on', models.DateTimeField(auto_now_add=True)),
                ('book_return', models.BooleanField(default=True)),
                ('returned_on', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rented_book', to='books.book')),
                ('borrow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_borrower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-borrowed_on'],
            },
        ),
    ]
