# Generated by Django 4.0.5 on 2022-07-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_borrowbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='book_return',
            field=models.BooleanField(default=False),
        ),
    ]
