# Generated by Django 4.0.5 on 2022-07-06 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0024_alter_borrowbook_book_return'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='BookComments',
        ),
    ]
