# Generated by Django 4.0.5 on 2022-07-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_rename_comment_bookcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcomments',
            old_name='content',
            new_name='bookcontent',
        ),
    ]
