# Generated by Django 4.0.5 on 2022-07-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_rename_content_bookcomments_bookcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomments',
            name='user_firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bookcomments',
            name='user_lastname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
